import type { GameCard } from './types';

export const districtSets = [
  { name: 'Harbor', size: 2, accent: '#22a6b3' },
  { name: 'Old Town', size: 2, accent: '#8b5a3c' },
  { name: 'Utilities', size: 2, accent: '#9ca3af' },
  { name: 'Gardens', size: 3, accent: '#55b86f' },
  { name: 'Sunset', size: 3, accent: '#f2d33d' },
  { name: 'Ember', size: 3, accent: '#df4b45' },
  { name: 'Bazaar', size: 3, accent: '#f39c12' },
  { name: 'Neon', size: 3, accent: '#e65f9f' },
  { name: 'Skyline', size: 3, accent: '#77bde8' },
  { name: 'Transit', size: 4, accent: '#2f3542' }
];

export const starterDeck: GameCard[] = [
  { id: 'p-harbor-1', name: 'Harbor Plot', type: 'property', value: 4, text: 'A premium waterfront anchor.', accent: '#22a6b3', district: 'Harbor', setSize: 2 },
  { id: 'p-harbor-2', name: 'Dockside Loft', type: 'property', value: 4, text: 'Completes fast waterfront sets.', accent: '#22a6b3', district: 'Harbor', setSize: 2 },
  { id: 'p-old-1', name: 'Brick Row', type: 'property', value: 1, text: 'A compact old town starter.', accent: '#8b5a3c', district: 'Old Town', setSize: 2 },
  { id: 'p-old-2', name: 'Copper Court', type: 'property', value: 1, text: 'Small value, useful finish.', accent: '#8b5a3c', district: 'Old Town', setSize: 2 },
  { id: 'p-utility-1', name: 'Water Works', type: 'property', value: 2, text: 'Utility pressure with steady value.', accent: '#9ca3af', district: 'Utilities', setSize: 2 },
  { id: 'p-utility-2', name: 'Power Plant', type: 'property', value: 2, text: 'Pair with another utility to close.', accent: '#9ca3af', district: 'Utilities', setSize: 2 },
  { id: 'p-garden-1', name: 'Garden Walk', type: 'property', value: 4, text: 'A flexible green district piece.', accent: '#55b86f', district: 'Gardens', setSize: 3 },
  { id: 'p-garden-2', name: 'Park Terrace', type: 'property', value: 4, text: 'A leafy Gardens property.', accent: '#55b86f', district: 'Gardens', setSize: 3 },
  { id: 'p-garden-3', name: 'Glasshouse Row', type: 'property', value: 4, text: 'Completes the Gardens district.', accent: '#55b86f', district: 'Gardens', setSize: 3 },
  { id: 'p-sunset-1', name: 'Market Mile', type: 'property', value: 3, text: 'A busy yellow rent anchor.', accent: '#f2d33d', district: 'Sunset', setSize: 3 },
  { id: 'p-sunset-2', name: 'Transit Corner', type: 'property', value: 3, text: 'Pairs well with action pressure.', accent: '#f2d33d', district: 'Sunset', setSize: 3 },
  { id: 'p-sunset-3', name: 'Central Arcade', type: 'property', value: 3, text: 'Completes a busy district.', accent: '#f2d33d', district: 'Sunset', setSize: 3 },
  { id: 'p-ember-1', name: 'Ruby Lane', type: 'property', value: 3, text: 'Strong red district value.', accent: '#df4b45', district: 'Ember', setSize: 3 },
  { id: 'p-ember-2', name: 'Festival Street', type: 'property', value: 3, text: 'A lively Ember property.', accent: '#df4b45', district: 'Ember', setSize: 3 },
  { id: 'p-ember-3', name: 'Cinder Avenue', type: 'property', value: 3, text: 'Finishes an Ember run.', accent: '#df4b45', district: 'Ember', setSize: 3 },
  { id: 'p-bazaar-1', name: 'Bazaar Gate', type: 'property', value: 2, text: 'Orange district opening piece.', accent: '#f39c12', district: 'Bazaar', setSize: 3 },
  { id: 'p-bazaar-2', name: 'Lantern Market', type: 'property', value: 2, text: 'A warm middle-value property.', accent: '#f39c12', district: 'Bazaar', setSize: 3 },
  { id: 'p-bazaar-3', name: 'Spice Square', type: 'property', value: 2, text: 'Completes a Bazaar district.', accent: '#f39c12', district: 'Bazaar', setSize: 3 },
  { id: 'p-neon-1', name: 'Neon Avenue', type: 'property', value: 2, text: 'High attention, quick pressure.', accent: '#e65f9f', district: 'Neon', setSize: 3 },
  { id: 'p-neon-2', name: 'Electric Square', type: 'property', value: 2, text: 'Bright district momentum.', accent: '#e65f9f', district: 'Neon', setSize: 3 },
  { id: 'p-neon-3', name: 'Glow Plaza', type: 'property', value: 2, text: 'Completes a Neon district.', accent: '#e65f9f', district: 'Neon', setSize: 3 },
  { id: 'p-sky-1', name: 'Cloud Court', type: 'property', value: 1, text: 'Light blue tempo property.', accent: '#77bde8', district: 'Skyline', setSize: 3 },
  { id: 'p-sky-2', name: 'Breeze Lane', type: 'property', value: 1, text: 'Cheap and useful set filler.', accent: '#77bde8', district: 'Skyline', setSize: 3 },
  { id: 'p-sky-3', name: 'Aero Terrace', type: 'property', value: 1, text: 'Completes a Skyline district.', accent: '#77bde8', district: 'Skyline', setSize: 3 },
  { id: 'p-transit-1', name: 'Ironworks Line', type: 'property', value: 2, text: 'One stop toward a long set.', accent: '#2f3542', district: 'Transit', setSize: 4 },
  { id: 'p-transit-2', name: 'Forge Station', type: 'property', value: 2, text: 'Transit district pressure.', accent: '#2f3542', district: 'Transit', setSize: 4 },
  { id: 'p-transit-3', name: 'North Terminal', type: 'property', value: 2, text: 'A sturdy transit piece.', accent: '#2f3542', district: 'Transit', setSize: 4 },
  { id: 'p-transit-4', name: 'Central Platform', type: 'property', value: 2, text: 'Completes a four-card route.', accent: '#2f3542', district: 'Transit', setSize: 4 },

  { id: 'w-harbor-garden', name: 'Harbor Garden Lease', type: 'wild', value: 4, text: 'Choose Harbor or Gardens when played.', accent: '#22a6b3', district: 'Wildcard', wildDistricts: ['Harbor', 'Gardens'] },
  { id: 'w-garden-transit', name: 'Garden Transit Lease', type: 'wild', value: 4, text: 'Choose Gardens or Transit when played.', accent: '#55b86f', district: 'Wildcard', wildDistricts: ['Gardens', 'Transit'] },
  { id: 'w-utility-transit', name: 'Utility Transit Lease', type: 'wild', value: 2, text: 'Choose Utilities or Transit when played.', accent: '#9ca3af', district: 'Wildcard', wildDistricts: ['Utilities', 'Transit'] },
  { id: 'w-sky-transit', name: 'Skyline Transit Lease', type: 'wild', value: 4, text: 'Choose Skyline or Transit when played.', accent: '#77bde8', district: 'Wildcard', wildDistricts: ['Skyline', 'Transit'] },
  { id: 'w-sky-old', name: 'Skyline Old Town Lease', type: 'wild', value: 1, text: 'Choose Skyline or Old Town when played.', accent: '#77bde8', district: 'Wildcard', wildDistricts: ['Skyline', 'Old Town'] },
  { id: 'w-neon-bazaar-a', name: 'Neon Bazaar Lease', type: 'wild', value: 2, text: 'Choose Neon or Bazaar when played.', accent: '#e65f9f', district: 'Wildcard', wildDistricts: ['Neon', 'Bazaar'] },
  { id: 'w-neon-bazaar-b', name: 'Bazaar Neon Lease', type: 'wild', value: 2, text: 'Choose Bazaar or Neon when played.', accent: '#f39c12', district: 'Wildcard', wildDistricts: ['Bazaar', 'Neon'] },
  { id: 'w-ember-sunset-a', name: 'Ember Sunset Lease', type: 'wild', value: 3, text: 'Choose Ember or Sunset when played.', accent: '#df4b45', district: 'Wildcard', wildDistricts: ['Ember', 'Sunset'] },
  { id: 'w-ember-sunset-b', name: 'Sunset Ember Lease', type: 'wild', value: 3, text: 'Choose Sunset or Ember when played.', accent: '#f2d33d', district: 'Wildcard', wildDistricts: ['Sunset', 'Ember'] },
  { id: 'w-all-a', name: 'Wildcard Lease', type: 'wild', value: 0, text: 'Can join any property district.', accent: '#7b61ff', district: 'Wildcard', wildDistricts: districtSets.map((district) => district.name) },
  { id: 'w-all-b', name: 'Open Lease', type: 'wild', value: 0, text: 'Can join any property district.', accent: '#7b61ff', district: 'Wildcard', wildDistricts: districtSets.map((district) => district.name) },

  { id: 'm-1', name: 'Petty Cash', type: 'money', value: 1, text: 'Bank it for small payments.', accent: '#b7d7a8' },
  { id: 'm-2', name: 'Cash Stack', type: 'money', value: 2, text: 'Bank it for protection.', accent: '#30b26b' },
  { id: 'm-3', name: 'Vault Notes', type: 'money', value: 3, text: 'A solid bank buffer.', accent: '#6dbd6d' },
  { id: 'm-4', name: 'Capital Bundle', type: 'money', value: 4, text: 'Big money for bigger turns.', accent: '#78b8e8' },
  { id: 'm-5', name: 'Vault Boost', type: 'money', value: 5, text: 'Heavy bank protection.', accent: '#78c850' },
  { id: 'm-10', name: 'Reserve Crown', type: 'money', value: 10, text: 'A rare reserve for major payments.', accent: '#d6a93a' },

  { id: 'a-deal-breaker', name: 'Deal Breaker', type: 'action', value: 5, text: 'Take one complete rival property district.', accent: '#c0392b', actionKind: 'stealSet' },
  { id: 'a-plot-grab', name: 'Plot Grab', type: 'action', value: 3, text: 'Take one loose property.', accent: '#d84f4f', actionKind: 'stealProperty' },
  { id: 'a-street-swap', name: 'Street Swap', type: 'action', value: 3, text: 'Trade one property with another player.', accent: '#6d71d9', actionKind: 'swapProperty' },
  { id: 'a-rent-rush', name: 'Rent Rush', type: 'action', value: 3, text: 'Choose a rival. They pay 3M from bank or properties.', accent: '#ef7d32', actionKind: 'rent' },
  { id: 'a-celebration', name: 'Celebration Collection', type: 'action', value: 2, text: 'Every rival pays 2M from their bank.', accent: '#f39c12', actionKind: 'birthday' },
  { id: 'a-permit-push', name: 'Permit Push', type: 'action', value: 1, text: 'Draw two cards.', accent: '#38a3a5', actionKind: 'draw' },
  { id: 'a-double-rent', name: 'Double Up', type: 'action', value: 1, text: 'Pair with a rent play to double pressure.', accent: '#c77d48', actionKind: 'doubleRent' },
  { id: 'a-house', name: 'Block Works', type: 'action', value: 3, text: 'Develop one complete district. Adds 3M to its rent value.', accent: '#2f80a8', actionKind: 'house' },
  { id: 'a-hotel', name: 'Skyline Landmark', type: 'action', value: 4, text: 'Upgrade a developed complete district. Adds 4M to its rent value.', accent: '#d94c5c', actionKind: 'hotel' },
  { id: 'd-hard-pass', name: 'Just Say No', type: 'defense', value: 4, text: 'Cancel the next action aimed at you.', accent: '#2f3542', actionKind: 'block' },

  { id: 'r-harbor-garden', name: 'Harbor Gardens Rent', type: 'rent', value: 2, text: 'Charge rent from Harbor or Gardens.', accent: '#22a6b3', actionKind: 'rent' },
  { id: 'r-ember-sunset', name: 'Ember Sunset Rent', type: 'rent', value: 2, text: 'Charge rent from Ember or Sunset.', accent: '#df4b45', actionKind: 'rent' },
  { id: 'r-neon-bazaar', name: 'Neon Bazaar Rent', type: 'rent', value: 2, text: 'Charge rent from Neon or Bazaar.', accent: '#e65f9f', actionKind: 'rent' },
  { id: 'r-sky-old', name: 'Skyline Old Town Rent', type: 'rent', value: 1, text: 'Charge rent from Skyline or Old Town.', accent: '#77bde8', actionKind: 'rent' },
  { id: 'r-transit-utility', name: 'Transit Utility Rent', type: 'rent', value: 2, text: 'Charge rent from Transit or Utilities.', accent: '#2f3542', actionKind: 'rent' },
  { id: 'r-wild', name: 'Wildcard Rent', type: 'rent', value: 3, text: 'Choose one rival and one owned district to charge.', accent: '#7b61ff', actionKind: 'rent' }
];

export const starterDeckCounts: Record<string, number> = {
  'm-1': 6,
  'm-2': 5,
  'm-3': 3,
  'm-4': 3,
  'm-5': 2,
  'm-10': 1,
  'a-deal-breaker': 2,
  'd-hard-pass': 3,
  'a-permit-push': 10,
  'a-street-swap': 3,
  'a-plot-grab': 3,
  'a-rent-rush': 3,
  'a-celebration': 3,
  'a-double-rent': 2,
  'a-house': 3,
  'a-hotel': 2,
  'r-harbor-garden': 2,
  'r-ember-sunset': 2,
  'r-neon-bazaar': 2,
  'r-sky-old': 2,
  'r-transit-utility': 2,
  'r-wild': 3
};
